version: "3.7"

services:
  sharify:
    build: .
    restart: always
    ports:
      - 8500:80
    networks:
      default:
      internal:

  cache:
    image: redis:4
    restart: always
    volumes:
      - .data/redis:/data
    networks:
      internal:

networks:
  internal:
    internal: true

